name: Build Skia with GLES

on:
  workflow_dispatch:
    inputs:
      skip_release:
        description: 'Skip release related steps? (true/false)'
        required: true
        default: 'true'

permissions:
  contents: write

env:
  version: m138-80d088a-1-gles  # Your custom version

jobs:
  macos:
    runs-on: ${{ fromJson('{"macos":"macos-13","ios":"macos-13","iosSim":"macos-13","tvos":"macos-13","tvosSim":"macos-13"}')[matrix.target] }}
    strategy:
      matrix:
        target: ["macos", "ios", "iosSim", "tvos", "tvosSim"]
        machine: ["x64", "arm64"]
        exclude:
          - target: tvos
            machine: x64
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: python3 script/check_release.py --version ${{ env.version }} --target ${{ matrix.target }} --build-type Release --machine ${{ matrix.machine }}
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Xcode version
        run: xcodebuild -version
      - run: python3 script/checkout.py --version ${{ env.version }}
      - run: python3 script/patch_sources.py --sources skia
      - run: python3 script/build.py --build-type Release --target ${{ matrix.target }} --machine ${{ matrix.machine }}
      - run: python3 script/archive.py --version ${{ env.version }} --build-type Release --target ${{ matrix.target }} --machine ${{ matrix.machine }}
      - uses: actions/upload-artifact@v4
        with:
          name: Skia-${{ env.version }}-${{ matrix.target }}-Release-${{ matrix.machine }}.zip
          path: '*.zip'
      - run: python3 script/release.py --version ${{ env.version }} --build-type Release --target ${{ matrix.target }} --machine ${{ matrix.machine }}
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - uses: actions/checkout@v2
      - run: ./script/prepare_linux.sh
      - run: python3 script/check_release.py --version ${{ env.version }} --build-type Release
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/checkout.py --version ${{ env.version }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/patch_sources.py --sources skia
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/build.py --build-type Release
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH python3 script/archive.py --version ${{ env.version }} --build-type Release
      - uses: actions/upload-artifact@v4
        with:
          name: Skia-${{ env.version }}-linux-Release-x64.zip
          path: '*.zip'
      - run: python3 script/release.py --version ${{ env.version }} --build-type Release
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-wasm:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - uses: actions/checkout@v2
      - run: ./script/prepare_linux_wasm.sh
      - run: python3 script/check_release.py --version ${{ env.version }} --target wasm --build-type Release --machine wasm
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: python3 script/checkout.py --version ${{ env.version }}
      - run: python3 script/patch_sources.py --sources skia
      - run: python3 script/build.py --target wasm --machine wasm --build-type Release
      - run: python3 script/archive.py --version ${{ env.version }} --target wasm --machine wasm --build-type Release
      - uses: actions/upload-artifact@v4
        with:
          name: Skia-${{ env.version }}-wasm-Release-wasm.zip
          path: '*.zip'
      - run: python3 script/release.py --version ${{ env.version }} --target wasm --machine wasm --build-type Release
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-android:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    strategy:
      matrix:
        machine: ["x64", "arm64"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: ./script/prepare_linux.sh
      - run: python3 script/check_release.py --version ${{ env.version }} --target android --build-type Release --machine ${{ matrix.machine }}
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: python3 script/checkout.py --version ${{ env.version }}
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
      - run: python3 script/patch_sources.py --sources skia
      - run: python3 script/build.py --target android --build-type Release --machine ${{ matrix.machine }} --ndk ${{ steps.setup-ndk.outputs.ndk-path }}
      - run: python3 script/archive.py --version ${{ env.version }} --target android --build-type Release --machine ${{ matrix.machine }}
      - uses: actions/upload-artifact@v4
        with:
          name: Skia-${{ env.version }}-android-Release-${{ matrix.machine }}.zip
          path: '*.zip'
      - run: python3 script/release.py --version ${{ env.version }} --target android --build-type Release --machine ${{ matrix.machine }}
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        name: Assemble
        with:
          image: arm64v8/ubuntu:20.04
          options: -v ${{ github.workspace }}:/checkout -e BUILD_VERSION=${{ env.version }}
          shell: /bin/bash
          run: |
            cd /checkout
            /bin/bash script/prepare_linux_arm.sh
            python3 script/check_release.py --version ${BUILD_VERSION} --build-type Release
            python3 script/checkout.py --version ${BUILD_VERSION}
            python3 script/patch_sources.py --sources skia
            python3 script/build.py --build-type Release
            python3 script/archive.py --version ${BUILD_VERSION} --build-type Release
      - uses: actions/upload-artifact@v4
        with:
          name: Skia-${{ env.version }}-linux-Release-arm64.zip
          path: '*.zip'
      - run: python3 script/release.py --version ${{ env.version }} --build-type Release --target linux --machine arm64
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    runs-on: windows-2022
    strategy:
      matrix:
        machine: ["x64", "arm64"]
      fail-fast: false
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - shell: bash
        run: python3 script/check_release.py --version ${{ env.version }} --build-type Release --target windows --machine ${{ matrix.machine }}
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: microsoft/setup-msbuild@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - shell: bash
        run: python3 script/checkout.py --version ${{ env.version }}
      - shell: bash
        run: python3 script/patch_sources.py --sources skia
      - shell: bash
        run: python3 script/build.py --build-type Release --target windows --machine ${{ matrix.machine }}
      - shell: bash
        run: python3 script/archive.py --version ${{ env.version }} --build-type Release --target windows --machine ${{ matrix.machine }}
      - uses: actions/upload-artifact@v4
        with:
          name: Skia-${{ env.version }}-windows-Release-${{ matrix.machine }}.zip
          path: '*.zip'
      - shell: bash
        run: python3 script/release.py --version ${{ env.version }} --build-type Release --target windows --machine ${{ matrix.machine }}
        if: ${{ github.event.inputs.skip_release != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
